// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hotstuff.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Sign verify part cert info
type PartCert struct {
	ReplicaId            int64    `protobuf:"varint,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PartCert) Reset()         { *m = PartCert{} }
func (m *PartCert) String() string { return proto.CompactTextString(m) }
func (*PartCert) ProtoMessage()    {}
func (*PartCert) Descriptor() ([]byte, []int) {
	return fileDescriptor_8517aa0e19c54851, []int{0}
}

func (m *PartCert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartCert.Unmarshal(m, b)
}
func (m *PartCert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartCert.Marshal(b, m, deterministic)
}
func (m *PartCert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartCert.Merge(m, src)
}
func (m *PartCert) XXX_Size() int {
	return xxx_messageInfo_PartCert.Size(m)
}
func (m *PartCert) XXX_DiscardUnknown() {
	xxx_messageInfo_PartCert.DiscardUnknown(m)
}

var xxx_messageInfo_PartCert proto.InternalMessageInfo

func (m *PartCert) GetReplicaId() int64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *PartCert) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

// QuorumCert is a data type that combines a collection of signatures from replicas.
type QuorumCert struct {
	// The hash of block data.
	BlockHash []byte `protobuf:"bytes,1,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	// the votes of the leader gathered from replicas for proposal.
	Signs                map[int64]*PartCert `protobuf:"bytes,2,rep,name=signs,proto3" json:"signs,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *QuorumCert) Reset()         { *m = QuorumCert{} }
func (m *QuorumCert) String() string { return proto.CompactTextString(m) }
func (*QuorumCert) ProtoMessage()    {}
func (*QuorumCert) Descriptor() ([]byte, []int) {
	return fileDescriptor_8517aa0e19c54851, []int{1}
}

func (m *QuorumCert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuorumCert.Unmarshal(m, b)
}
func (m *QuorumCert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuorumCert.Marshal(b, m, deterministic)
}
func (m *QuorumCert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuorumCert.Merge(m, src)
}
func (m *QuorumCert) XXX_Size() int {
	return xxx_messageInfo_QuorumCert.Size(m)
}
func (m *QuorumCert) XXX_DiscardUnknown() {
	xxx_messageInfo_QuorumCert.DiscardUnknown(m)
}

var xxx_messageInfo_QuorumCert proto.InternalMessageInfo

func (m *QuorumCert) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

func (m *QuorumCert) GetSigns() map[int64]*PartCert {
	if m != nil {
		return m.Signs
	}
	return nil
}

// The wrapper of block struct
type Block struct {
	// parent_hash is the parent hash of the block
	ParentHash []byte `protobuf:"bytes,1,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	// Any data needed to exec, like: block, tx...
	Cmds []byte `protobuf:"bytes,2,opt,name=cmds,proto3" json:"cmds,omitempty"`
	// The miner's address of current block
	Proposer string `protobuf:"bytes,3,opt,name=proposer,proto3" json:"proposer,omitempty"`
	// The height of the blockchain
	Height int64 `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	// Timestamp of the block
	Timestamp int64 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// qc of cmd for parent block
	Justify *QuorumCert `protobuf:"bytes,6,opt,name=justify,proto3" json:"justify,omitempty"`
	// qc of cmd for self
	SelfQc               *QuorumCert `protobuf:"bytes,7,opt,name=self_qc,json=selfQc,proto3" json:"self_qc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_8517aa0e19c54851, []int{2}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetParentHash() []byte {
	if m != nil {
		return m.ParentHash
	}
	return nil
}

func (m *Block) GetCmds() []byte {
	if m != nil {
		return m.Cmds
	}
	return nil
}

func (m *Block) GetProposer() string {
	if m != nil {
		return m.Proposer
	}
	return ""
}

func (m *Block) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Block) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Block) GetJustify() *QuorumCert {
	if m != nil {
		return m.Justify
	}
	return nil
}

func (m *Block) GetSelfQc() *QuorumCert {
	if m != nil {
		return m.SelfQc
	}
	return nil
}

// Types of communication messages between replicas
type Message struct {
	// Types that are valid to be assigned to Type:
	//	*Message_NewView
	//	*Message_Proposal
	//	*Message_Vote
	Type                 isMessage_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_8517aa0e19c54851, []int{3}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

type isMessage_Type interface {
	isMessage_Type()
}

type Message_NewView struct {
	NewView *NewView `protobuf:"bytes,1,opt,name=new_view,json=newView,proto3,oneof"`
}

type Message_Proposal struct {
	Proposal *Proposal `protobuf:"bytes,2,opt,name=proposal,proto3,oneof"`
}

type Message_Vote struct {
	Vote *Vote `protobuf:"bytes,3,opt,name=vote,proto3,oneof"`
}

func (*Message_NewView) isMessage_Type() {}

func (*Message_Proposal) isMessage_Type() {}

func (*Message_Vote) isMessage_Type() {}

func (m *Message) GetType() isMessage_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Message) GetNewView() *NewView {
	if x, ok := m.GetType().(*Message_NewView); ok {
		return x.NewView
	}
	return nil
}

func (m *Message) GetProposal() *Proposal {
	if x, ok := m.GetType().(*Message_Proposal); ok {
		return x.Proposal
	}
	return nil
}

func (m *Message) GetVote() *Vote {
	if x, ok := m.GetType().(*Message_Vote); ok {
		return x.Vote
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Message) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Message_NewView)(nil),
		(*Message_Proposal)(nil),
		(*Message_Vote)(nil),
	}
}

// new view msg
type NewView struct {
	GenericQc            *QuorumCert `protobuf:"bytes,1,opt,name=generic_qc,json=genericQc,proto3" json:"generic_qc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *NewView) Reset()         { *m = NewView{} }
func (m *NewView) String() string { return proto.CompactTextString(m) }
func (*NewView) ProtoMessage()    {}
func (*NewView) Descriptor() ([]byte, []int) {
	return fileDescriptor_8517aa0e19c54851, []int{4}
}

func (m *NewView) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewView.Unmarshal(m, b)
}
func (m *NewView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewView.Marshal(b, m, deterministic)
}
func (m *NewView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewView.Merge(m, src)
}
func (m *NewView) XXX_Size() int {
	return xxx_messageInfo_NewView.Size(m)
}
func (m *NewView) XXX_DiscardUnknown() {
	xxx_messageInfo_NewView.DiscardUnknown(m)
}

var xxx_messageInfo_NewView proto.InternalMessageInfo

func (m *NewView) GetGenericQc() *QuorumCert {
	if m != nil {
		return m.GenericQc
	}
	return nil
}

// broadcast proposal to other replicas
type Proposal struct {
	Proposer             int64    `protobuf:"varint,1,opt,name=proposer,proto3" json:"proposer,omitempty"`
	Block                *Block   `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Proposal) Reset()         { *m = Proposal{} }
func (m *Proposal) String() string { return proto.CompactTextString(m) }
func (*Proposal) ProtoMessage()    {}
func (*Proposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_8517aa0e19c54851, []int{5}
}

func (m *Proposal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proposal.Unmarshal(m, b)
}
func (m *Proposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proposal.Marshal(b, m, deterministic)
}
func (m *Proposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proposal.Merge(m, src)
}
func (m *Proposal) XXX_Size() int {
	return xxx_messageInfo_Proposal.Size(m)
}
func (m *Proposal) XXX_DiscardUnknown() {
	xxx_messageInfo_Proposal.DiscardUnknown(m)
}

var xxx_messageInfo_Proposal proto.InternalMessageInfo

func (m *Proposal) GetProposer() int64 {
	if m != nil {
		return m.Proposer
	}
	return 0
}

func (m *Proposal) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

// Vote messages
type Vote struct {
	// Voter replica id
	Voter int64 `protobuf:"varint,1,opt,name=voter,proto3" json:"voter,omitempty"`
	// The hash of block being voted
	BlockHash []byte `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	// Proof of validity for the vote
	Cert                 *PartCert `protobuf:"bytes,3,opt,name=cert,proto3" json:"cert,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Vote) Reset()         { *m = Vote{} }
func (m *Vote) String() string { return proto.CompactTextString(m) }
func (*Vote) ProtoMessage()    {}
func (*Vote) Descriptor() ([]byte, []int) {
	return fileDescriptor_8517aa0e19c54851, []int{6}
}

func (m *Vote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vote.Unmarshal(m, b)
}
func (m *Vote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vote.Marshal(b, m, deterministic)
}
func (m *Vote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vote.Merge(m, src)
}
func (m *Vote) XXX_Size() int {
	return xxx_messageInfo_Vote.Size(m)
}
func (m *Vote) XXX_DiscardUnknown() {
	xxx_messageInfo_Vote.DiscardUnknown(m)
}

var xxx_messageInfo_Vote proto.InternalMessageInfo

func (m *Vote) GetVoter() int64 {
	if m != nil {
		return m.Voter
	}
	return 0
}

func (m *Vote) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

func (m *Vote) GetCert() *PartCert {
	if m != nil {
		return m.Cert
	}
	return nil
}

func init() {
	proto.RegisterType((*PartCert)(nil), "pb.PartCert")
	proto.RegisterType((*QuorumCert)(nil), "pb.QuorumCert")
	proto.RegisterMapType((map[int64]*PartCert)(nil), "pb.QuorumCert.SignsEntry")
	proto.RegisterType((*Block)(nil), "pb.Block")
	proto.RegisterType((*Message)(nil), "pb.Message")
	proto.RegisterType((*NewView)(nil), "pb.NewView")
	proto.RegisterType((*Proposal)(nil), "pb.Proposal")
	proto.RegisterType((*Vote)(nil), "pb.Vote")
}

func init() { proto.RegisterFile("hotstuff.proto", fileDescriptor_8517aa0e19c54851) }

var fileDescriptor_8517aa0e19c54851 = []byte{
	// 489 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0xcd, 0x8e, 0xd3, 0x3c,
	0x14, 0x6d, 0xd2, 0xfc, 0x34, 0x37, 0xd5, 0xe8, 0x93, 0xf5, 0x09, 0x85, 0x11, 0x30, 0x51, 0x36,
	0x44, 0x48, 0x14, 0xa9, 0x6c, 0x46, 0x2c, 0x07, 0x01, 0x65, 0x01, 0xa2, 0x46, 0x9a, 0x1d, 0xaa,
	0xdc, 0xf4, 0xb6, 0x09, 0x93, 0x26, 0xc1, 0x76, 0x5a, 0xf5, 0x09, 0x78, 0x11, 0x5e, 0x8c, 0x37,
	0x41, 0x76, 0x9c, 0x76, 0x3a, 0x9a, 0x9d, 0x7d, 0xce, 0xbd, 0x37, 0xe7, 0x1c, 0xdf, 0xc0, 0x45,
	0x5e, 0x4b, 0x21, 0xdb, 0xf5, 0x7a, 0xd2, 0xf0, 0x5a, 0xd6, 0xc4, 0x6e, 0x96, 0xc9, 0x27, 0x18,
	0x7d, 0x63, 0x5c, 0xbe, 0x47, 0x2e, 0xc9, 0x73, 0x00, 0x8e, 0x4d, 0x59, 0x64, 0x6c, 0x51, 0xac,
	0x22, 0x2b, 0xb6, 0xd2, 0x21, 0x0d, 0x0c, 0xf2, 0x79, 0x45, 0x9e, 0x41, 0x20, 0x8a, 0x4d, 0xc5,
	0x64, 0xcb, 0x31, 0xb2, 0x63, 0x2b, 0x1d, 0xd3, 0x13, 0x90, 0xfc, 0xb1, 0x00, 0xe6, 0x6d, 0xcd,
	0xdb, 0x6d, 0x3f, 0x6b, 0x59, 0xd6, 0xd9, 0xdd, 0x22, 0x67, 0x22, 0xd7, 0xb3, 0xc6, 0x34, 0xd0,
	0xc8, 0x8c, 0x89, 0x9c, 0xbc, 0x01, 0x57, 0xb5, 0x8a, 0xc8, 0x8e, 0x87, 0x69, 0x38, 0x7d, 0x3a,
	0x69, 0x96, 0x93, 0x53, 0xf7, 0xe4, 0xbb, 0xe2, 0x3e, 0x54, 0x92, 0x1f, 0x68, 0x57, 0x77, 0xf9,
	0x11, 0xe0, 0x04, 0x92, 0xff, 0x60, 0x78, 0x87, 0x07, 0x23, 0x51, 0x1d, 0x49, 0x02, 0xee, 0x8e,
	0x95, 0x6d, 0x27, 0x2c, 0x9c, 0x8e, 0xd5, 0xc0, 0xde, 0x18, 0xed, 0xa8, 0x77, 0xf6, 0xb5, 0x95,
	0xfc, 0xb5, 0xc0, 0xbd, 0x51, 0x32, 0xc8, 0x15, 0x84, 0x0d, 0xe3, 0x58, 0xc9, 0xfb, 0x12, 0xa1,
	0x83, 0xb4, 0x46, 0x02, 0x4e, 0xb6, 0x5d, 0x09, 0x63, 0x55, 0x9f, 0xc9, 0x25, 0x8c, 0x1a, 0x5e,
	0x37, 0xb5, 0x40, 0x1e, 0x0d, 0x63, 0x2b, 0x0d, 0xe8, 0xf1, 0x4e, 0x9e, 0x80, 0x97, 0x63, 0xb1,
	0xc9, 0x65, 0xe4, 0x68, 0x5d, 0xe6, 0xa6, 0x72, 0x93, 0xc5, 0x16, 0x85, 0x64, 0xdb, 0x26, 0x72,
	0xbb, 0x54, 0x8f, 0x00, 0x49, 0xc1, 0xff, 0xd9, 0x0a, 0x59, 0xac, 0x0f, 0x91, 0xa7, 0xa5, 0x5f,
	0x9c, 0x67, 0x41, 0x7b, 0x9a, 0xbc, 0x04, 0x5f, 0x60, 0xb9, 0x5e, 0xfc, 0xca, 0x22, 0xff, 0xd1,
	0x4a, 0x4f, 0xd1, 0xf3, 0x2c, 0xf9, 0x6d, 0x81, 0xff, 0x05, 0x85, 0x60, 0x1b, 0x24, 0x29, 0x8c,
	0x2a, 0xdc, 0x2f, 0x76, 0x05, 0xee, 0xb5, 0xc5, 0x70, 0x1a, 0xaa, 0xae, 0xaf, 0xb8, 0xbf, 0x2d,
	0x70, 0x3f, 0x1b, 0x50, 0xbf, 0xea, 0x8e, 0xe4, 0x55, 0x6f, 0x8d, 0x95, 0x67, 0x21, 0x1a, 0x6c,
	0x36, 0xa0, 0x47, 0x9e, 0xbc, 0x00, 0x67, 0x57, 0x4b, 0xd4, 0x11, 0x84, 0xd3, 0x91, 0xaa, 0xbb,
	0xad, 0x25, 0xce, 0x06, 0x54, 0xe3, 0x37, 0x1e, 0x38, 0xf2, 0xd0, 0x60, 0x72, 0x0d, 0xbe, 0xf9,
	0x12, 0x79, 0x0d, 0xb0, 0xc1, 0x0a, 0x79, 0x91, 0x29, 0x03, 0xd6, 0xa3, 0x06, 0x02, 0x53, 0x31,
	0xcf, 0xf4, 0x5e, 0xf6, 0x5f, 0xbb, 0x1f, 0x7a, 0xf7, 0xe4, 0xa7, 0xd0, 0xaf, 0xc0, 0xd5, 0x5b,
	0x65, 0x24, 0x07, 0x6a, 0xa2, 0x7e, 0x5f, 0xda, 0xe1, 0xc9, 0x0f, 0x70, 0x94, 0x34, 0xf2, 0x3f,
	0xb8, 0x4a, 0x5a, 0x3f, 0xa1, 0xbb, 0x3c, 0x58, 0x53, 0xfb, 0xe1, 0x9a, 0xc6, 0xe0, 0x64, 0xc8,
	0xa5, 0xf1, 0x79, 0xbe, 0x54, 0x9a, 0x59, 0x7a, 0xfa, 0x57, 0x7a, 0xfb, 0x2f, 0x00, 0x00, 0xff,
	0xff, 0x86, 0x25, 0xf7, 0xc7, 0x5c, 0x03, 0x00, 0x00,
}
